#!/usr/bin/env python3
"""
PROTECT Data Manifest — index generator.

Reads every manifest/collections/<id>/dataset.yaml (+ the sibling CARD.md frontmatter) and
regenerates manifest/INDEX.md — the greppable catalog an agent reads first. Groups collections
by team (browse "what does Conrad produce") and provides a facet index (browse "where's the
clinical data"). Run after crawl.py. Never hand-edit INDEX.md.
"""
import os, glob, datetime
import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COLLECTIONS_DIR = os.path.join(REPO, "manifest", "collections")
INDEX = os.path.join(REPO, "manifest", "INDEX.md")


def card_frontmatter(card_path):
    if not os.path.isfile(card_path):
        return None
    try:
        with open(card_path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        return yaml.safe_load(parts[1]) or {}
    except Exception:
        return {}


def load_collections():
    rows = []
    for ds in sorted(glob.glob(os.path.join(COLLECTIONS_DIR, "*", "dataset.yaml"))):
        try:
            with open(ds) as f:
                d = yaml.safe_load(f)
        except Exception:
            continue
        cid = d.get("id") or os.path.basename(os.path.dirname(ds))
        card = card_frontmatter(os.path.join(os.path.dirname(ds), "CARD.md"))
        resources = d.get("resources") or []
        nfields = sum(len((r.get("schema") or {}).get("fields", [])) for r in resources)
        om = d.get("owner_manifest") or {}
        rows.append({
            "id": cid,
            "title": d.get("title", cid),
            "team": d.get("team") or "Unassigned",
            "domain": d.get("domain") or "",
            "tags": d.get("tags") or [],
            "access": (d.get("access") or {}).get("status", "unknown"),
            "root": d.get("collection_root", ""),
            "nresources": len(resources),
            "nfields": nfields,
            "nsub": len(d.get("subdirectories") or []),
            "mtime": (d.get("freshness") or {}).get("source_mtime_latest"),
            "owner_manifest": om.get("path"),
            "summary": (card or {}).get("summary", "") if card else "",
            "keywords": (card or {}).get("keywords", []) if card else [],
            "related": (card or {}).get("related", []) if card else [],
            "has_card": card is not None,
        })
    return rows


def _join(v):
    return ", ".join(v) if isinstance(v, list) else str(v)


def render(rows):
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    L = ["# PROTECT Data Manifest — Catalog", ""]
    L.append(f"_Auto-generated by `crawler/build_index.py` — {ts} · {len(rows)} collections. Do not hand-edit._")
    L += [
        "",
        "> **Agents start here.** Find a collection by **team** (below) or by **tag** (facet index at",
        "> the bottom), then open its **`CARD.md`** (meaning + join recipes) and **`dataset.yaml`**",
        "> (exact schema + file paths + per-subdirectory digest) under `manifest/collections/<id>/`.",
        "> Follow `related` to connect collections. Honor `access`. For cross-collection joins, see",
        "> **`manifest/LINKAGE.md`** (the join map).",
        "",
    ]

    # group by team
    teams = {}
    for r in rows:
        teams.setdefault(r["team"], []).append(r)

    L.append("## Collections by team")
    L.append("")
    for team in sorted(teams):
        L.append(f"### {team}")
        L.append("")
        for r in sorted(teams[team], key=lambda x: x["id"]):
            card = f"`{r['id']}/CARD.md`" if r["has_card"] else "⚠️ card not yet written"
            L.append(f"#### {r['title']} — `{r['id']}`  ·  domain: _{r['domain']}_  ·  access: **{r['access']}**")
            if r["summary"]:
                L.append(f"- **summary:** {r['summary']}")
            L.append(f"- **tags:** {_join(r['tags']) if r['tags'] else '—'}")
            if r["keywords"]:
                L.append(f"- **keywords:** {_join(r['keywords'])}")
            L.append(f"- **path:** `{r['root']}`")
            content = f"{r['nresources']} described file(s), {r['nfields']} fields"
            if r["nsub"]:
                content += f", {r['nsub']} subdirectories"
            L.append(f"- **content:** {content} · source_mtime: {r['mtime'] or '—'}")
            if r["owner_manifest"]:
                L.append(f"- **owner manifest (federated):** `{r['owner_manifest']}`")
            if r["related"]:
                L.append(f"- **related:** {_join(r['related'])}")
            L.append(f"- **card:** {card} · **descriptor:** `manifest/collections/{r['id']}/dataset.yaml`")
            L.append("")

    L += ["## Facet index (tag → collections)", ""]
    facets = {}
    for r in rows:
        for t in r["tags"]:
            facets.setdefault(t, []).append(r["id"])
    for t in sorted(facets):
        L.append(f"- **{t}:** {', '.join(sorted(facets[t]))}")
    L.append("")

    carded = sum(1 for r in rows if r["has_card"])
    L += ["## Coverage", "",
          f"- Collections: {len(rows)} · with human `CARD.md`: {carded} · awaiting card: {len(rows) - carded}",
          ""]
    return "\n".join(L)


def main():
    rows = load_collections()
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write(render(rows))
    print(f"wrote {os.path.relpath(INDEX, REPO)} — {len(rows)} collections, "
          f"{sum(1 for r in rows if r['has_card'])} with cards")


if __name__ == "__main__":
    main()
