#!/usr/bin/env python3
"""
PROTECT Data Manifest — freshness / diff report.

Compares the current catalog to the previous snapshot and writes manifest/FRESHNESS.md: what's
NEW, what CHANGED at the source since the last crawl, what's UNDOCUMENTED (no human card), and what
may be STALE (a card reviewed before its source last changed). This is the bounded nightly triage
list — run after crawl.py + build_index.py. Saves crawler/.last_snapshot.json for the next diff.
"""
import os, glob, json, datetime
import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COLLECTIONS_DIR = os.path.join(REPO, "manifest", "collections")
SNAP = os.path.join(REPO, "crawler", ".last_snapshot.json")
OUT = os.path.join(REPO, "manifest", "FRESHNESS.md")


def card_frontmatter(card_path):
    if not os.path.isfile(card_path):
        return None
    try:
        with open(card_path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        return yaml.safe_load(parts[1]) or {}
    except Exception:
        return {}


def current_state():
    state = {}
    for ds in sorted(glob.glob(os.path.join(COLLECTIONS_DIR, "*", "dataset.yaml"))):
        try:
            with open(ds) as f:
                d = yaml.safe_load(f)
        except Exception:
            continue
        cid = d.get("id") or os.path.basename(os.path.dirname(ds))
        card = card_frontmatter(os.path.join(os.path.dirname(ds), "CARD.md"))
        state[cid] = {
            "title": d.get("title", cid),
            "team": d.get("team"),
            "source_mtime_latest": (d.get("freshness") or {}).get("source_mtime_latest"),
            "file_count": (d.get("size") or {}).get("file_count"),
            "n_resources": len(d.get("resources") or []),
            "has_card": card is not None,
            "card_last_reviewed": str((card or {}).get("last_reviewed")) if card else None,
        }
    return state


def main():
    cur = current_state()
    prev = {}
    if os.path.exists(SNAP):
        try:
            with open(SNAP) as f:
                prev = json.load(f)
        except Exception:
            prev = {}

    now = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    baseline = not prev
    new = [c for c in cur if c not in prev]
    removed = [c for c in prev if c not in cur]
    changed = [c for c in cur if c in prev and (
        cur[c]["source_mtime_latest"] != prev[c].get("source_mtime_latest")
        or cur[c]["file_count"] != prev[c].get("file_count"))]
    undocumented = [c for c in cur if not cur[c]["has_card"]]
    stale = [c for c, v in cur.items()
             if v["has_card"] and v["card_last_reviewed"] and v["source_mtime_latest"]
             and v["card_last_reviewed"] < v["source_mtime_latest"][:10]]

    L = ["# PROTECT Data Manifest — Freshness Report", ""]
    L.append(f"_Auto-generated by `crawler/freshness_report.py` — {now}._")
    L.append("")
    if baseline:
        L.append("> **Baseline snapshot** (no previous state). Future runs will diff against this.")
        L.append("")

    def section(title, ids, how):
        L.append(f"## {title} ({len(ids)})")
        L.append("")
        if not ids:
            L.append("_none_")
        else:
            for c in sorted(ids):
                L.append(f"- `{c}` — {how(c)}")
        L.append("")

    if not baseline:
        section("🆕 New collections", new, lambda c: cur[c]["title"])
        section("✏️ Changed at source since last crawl", changed,
                lambda c: f"{cur[c]['title']} — source_mtime {prev[c].get('source_mtime_latest')} → {cur[c]['source_mtime_latest']}, files {prev[c].get('file_count')} → {cur[c]['file_count']}")
        section("🗑️ Removed", removed, lambda c: prev[c].get("title", c))
    section("⚠️ Undocumented (no human CARD.md)", undocumented, lambda c: cur[c]["title"])
    section("🕳️ Possibly-stale cards (source changed after last review)", stale,
            lambda c: f"{cur[c]['title']} — card reviewed {cur[c]['card_last_reviewed']}, source {cur[c]['source_mtime_latest']}")

    L.append("## Summary")
    L.append("")
    L.append(f"- Collections: {len(cur)} · undocumented: {len(undocumented)} · possibly-stale: {len(stale)}"
             + ("" if baseline else f" · new: {len(new)} · changed: {len(changed)} · removed: {len(removed)}"))
    L.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    with open(SNAP, "w", encoding="utf-8") as f:
        json.dump(cur, f, indent=2)
    print(f"wrote {os.path.relpath(OUT, REPO)} — {len(cur)} collections, "
          f"{len(undocumented)} undocumented, {len(stale)} possibly-stale"
          + ("" if baseline else f", {len(new)} new, {len(changed)} changed"))


if __name__ == "__main__":
    main()
